/**
 * InfusiLat — catálogo semilla.
 *
 * SERVER-ONLY. Este archivo no debe llegar nunca al bundle del cliente:
 * el `import 'server-only'` hace que la compilación falle si alguien lo
 * importa desde un componente cliente por accidente.
 *
 * Se entrega únicamente desde /api/infusilat/catalogo, tras comprobar la
 * suscripción. A partir del primer acceso cada usuario tiene su propia copia
 * en Supabase y este archivo ya no le afecta.
 *
 * Al cambiar el contenido, subir SEED_VERSION.
 */

import 'server-only';
import type { Catalogo, Farmaco, SetFarmacos } from './engine';

export const SEED_VERSION = 1;

/** Diluyentes ofrecidos en los selectores de la interfaz. */
export const DILUYENTES = [
  'SSN 0.9%',
  'DAD 5%',
  'agua estéril',
  'Ringer lactato',
  'sin diluir',
  'solución lista',
  'diluyente propio',
] as const;

export const CATS: Record<string, string> = {
  anest: 'Anestésicos / Sedación',
  opio: 'Opioides',
  analg: 'Analgesia no opioide',
  nmb: 'Relajantes musculares',
  rev: 'Reversores / Antídotos',
  vaso: 'Vasopresores / Inotrópicos',
  vdil: 'Vasodilatadores / Antihipertensivos',
  arrit: 'Antiarrítmicos',
  emet: 'Antieméticos / Neuro',
  atb: 'Antibióticos',
  hemo: 'Hemostasia / Anticoagulación',
  obst: 'Obstetricia',
  resp: 'Respiratorio / Esteroides',
  meta: 'Metabólico / Electrolitos',
};

export const DRUGS: Farmaco[] = [
  /* ---------- ANESTÉSICOS / SEDACIÓN ---------- */
  { id: 'propofol', n: 'Propofol', a: ['diprivan'], c: 'anest', fav: 1, pref: 'ajustado',
    inf: { u: 'mg/kg/hr', lo: 4, hi: 12, dil: { m: 1000, um: 'mg', v: 100, d: 'sin diluir (10 mg/mL)' } },
    bol: { u: 'mg/kg', lo: 1.5, hi: 2.5, dil: { m: 1000, um: 'mg', v: 100, d: 'sin diluir' } },
    nota: 'Mantenimiento TIVA 4–12 mg/kg/hr; sedación 1–4. Reducir 30–50 % en ancianos, hipovolemia o con opioide. Objetivo Schnider Ce 2.5–4 µg/mL.' },
  { id: 'ketamina', n: 'Ketamina', a: ['ketalar'], c: 'anest', fav: 1, alerta: 1,
    inf: { u: 'mg/kg/hr', lo: 0.1, hi: 0.5, dil: { m: 200, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 0.15, hi: 0.5, tope: 100, via: 'IV', dil: { m: 100, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Analgesia: bolo 0.15–0.5 mg/kg + infusión 0.1–0.3 mg/kg/hr (ahorra opioide, útil en dolor neuropático y tolerancia).\nInducción: 1–2 mg/kg IV / 4–6 mg/kg IM.\nSedación disociativa: 0.5–1 mg/kg.' },
  { id: 'dexmedetomidina', n: 'Dexmedetomidina', a: ['precedex', 'dexmed'], c: 'anest', fav: 1,
    inf: { u: 'mcg/kg/hr', lo: 0.2, hi: 1.4, dil: { m: 200, um: 'mcg', v: 50, d: 'SSN 0.9%' } },
    bol: { u: 'mcg/kg', lo: 0.5, hi: 1, tope: 100, via: 'IV en 10 min', dil: { m: 200, um: 'mcg', v: 50, d: 'SSN 0.9%' } },
    nota: 'Carga 1 µg/kg en 10 min (omitir si hay riesgo de bradicardia o hipotensión). Sin depresión respiratoria. Bradicardia e hipotensión dosis-dependientes.' },
  { id: 'midazolam', n: 'Midazolam', a: ['dormicum'], c: 'anest', fav: 1,
    inf: { u: 'mg/hr', lo: 1, hi: 10, dil: { m: 50, um: 'mg', v: 50, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 0.02, hi: 0.1, tope: 5, via: 'IV', dil: { m: 5, um: 'mg', v: 5, d: 'SSN 0.9%' } },
    nota: 'Premedicación 0.02–0.04 mg/kg. Pediatría VO 0.5 mg/kg (máx 20 mg). Antagonista: flumazenil.' },
  { id: 'etomidato', n: 'Etomidato', c: 'anest',
    bol: { u: 'mg/kg', lo: 0.2, hi: 0.3, tope: 40, via: 'IV', dil: { m: 20, um: 'mg', v: 10, d: 'sin diluir' } },
    nota: 'Estabilidad hemodinámica. Mioclonías; supresión adrenal tras dosis única (evitar infusión).' },
  { id: 'tiopental', n: 'Tiopental', c: 'anest',
    bol: { u: 'mg/kg', lo: 3, hi: 5, via: 'IV', dil: { m: 500, um: 'mg', v: 20, d: 'agua estéril (25 mg/mL)' } },
    nota: 'Inducción 3–5 mg/kg. Protección cerebral 1–2 mg/kg en bolos. Extravasación y arterial: necrosis.' },
  { id: 'lorazepam', n: 'Lorazepam', c: 'anest',
    bol: { u: 'mg', lo: 1, hi: 4, tope: 4, via: 'IV', dil: { m: 4, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Estatus epiléptico 0.1 mg/kg (máx 4 mg por dosis).' },
  { id: 'diazepam', n: 'Diazepam', c: 'anest',
    bol: { u: 'mg', lo: 2.5, hi: 10, tope: 10, via: 'IV lento', dil: { m: 10, um: 'mg', v: 2, d: 'sin diluir' } },
    nota: 'No diluir en SSN (precipita). Flebitis frecuente.' },
  { id: 'lidocaina-iv', n: 'Lidocaína (analgesia IV)', a: ['xilocaina'], c: 'anest', fav: 1,
    inf: { u: 'mg/kg/hr', lo: 1, hi: 2, dil: { m: 1000, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 1, hi: 1.5, tope: 100, via: 'IV en 10 min', dil: { m: 200, um: 'mg', v: 10, d: 'lidocaína 2%' } },
    nota: 'Analgesia sistémica perioperatoria: bolo 1.5 mg/kg + 1.5 mg/kg/hr intraoperatorio. Suspender al cierre. Vigilar toxicidad (acúfenos, sabor metálico). Usar peso magro.' },

  /* ---------- OPIOIDES ---------- */
  { id: 'fentanilo', n: 'Fentanilo', c: 'opio', fav: 1, alerta: 1,
    inf: { u: 'mcg/kg/hr', lo: 0.5, hi: 3, dil: { m: 1000, um: 'mcg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mcg/kg', lo: 0.5, hi: 3, tope: 250, via: 'IV', dil: { m: 500, um: 'mcg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Inducción 1–3 µg/kg. Rigidez torácica con bolos rápidos altos. Ce objetivo 2–4 ng/mL.' },
  { id: 'remifentanilo', n: 'Remifentanilo', a: ['ultiva'], c: 'opio', fav: 1, alerta: 1, pref: 'magro',
    inf: { u: 'mcg/kg/min', lo: 0.05, hi: 0.5, dil: { m: 2, um: 'mg', v: 40, d: 'SSN 0.9%' } },
    bol: { u: 'mcg/kg', lo: 0.5, hi: 1, via: 'IV en 30–60 s', dil: { m: 2, um: 'mg', v: 40, d: 'SSN 0.9%' } },
    nota: 'Dosificar por PESO MAGRO. Sin efecto residual: planificar analgesia antes de suspender. Hiperalgesia con dosis altas prolongadas.' },
  { id: 'morfina', n: 'Morfina', c: 'opio', fav: 1, alerta: 1,
    inf: { u: 'mg/hr', lo: 1, hi: 5, dil: { m: 50, um: 'mg', v: 50, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 0.05, hi: 0.15, tope: 10, via: 'IV', dil: { m: 10, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'PCA típica: bolo 1 mg, cierre 8 min, sin basal. Intratecal 100–200 µg (vigilancia 24 h).' },
  { id: 'hidromorfona', n: 'Hidromorfona', c: 'opio', alerta: 1,
    inf: { u: 'mg/hr', lo: 0.2, hi: 1, dil: { m: 10, um: 'mg', v: 50, d: 'SSN 0.9%' } },
    bol: { u: 'mg', lo: 0.2, hi: 0.6, tope: 2, via: 'IV', dil: { m: 2, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: '≈5–7 veces más potente que morfina. Preferible en insuficiencia renal.' },
  { id: 'sufentanilo', n: 'Sufentanilo', c: 'opio', alerta: 1,
    inf: { u: 'mcg/kg/hr', lo: 0.1, hi: 0.5, dil: { m: 250, um: 'mcg', v: 50, d: 'SSN 0.9%' } },
    bol: { u: 'mcg/kg', lo: 0.1, hi: 0.5, via: 'IV', dil: { m: 50, um: 'mcg', v: 10, d: 'SSN 0.9%' } },
    nota: '≈10× fentanilo. Peridural 10–20 µg con anestésico local.' },
  { id: 'alfentanilo', n: 'Alfentanilo', c: 'opio',
    inf: { u: 'mcg/kg/min', lo: 0.5, hi: 2, dil: { m: 5, um: 'mg', v: 50, d: 'SSN 0.9%' } },
    bol: { u: 'mcg/kg', lo: 10, hi: 30, via: 'IV', dil: { m: 5, um: 'mg', v: 10, d: 'sin diluir' } },
    nota: 'Inicio en 1–2 min: útil para intubación e instrumentación breve.' },
  { id: 'metadona', n: 'Metadona', c: 'opio', alerta: 1,
    bol: { u: 'mg', lo: 2.5, hi: 10, tope: 20, via: 'IV lento', dil: { m: 10, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: '0.1–0.2 mg/kg intraoperatoria reduce dolor y consumo de opioide 48 h. Antagonista NMDA. Vigilar QTc.' },
  { id: 'tramadol', n: 'Tramadol', c: 'opio',
    inf: { u: 'mg/hr', lo: 10, hi: 20, dil: { m: 400, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 1, hi: 1.5, tope: 100, via: 'IV lento', dil: { m: 100, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    nota: 'Máx 400 mg/día. Náusea si se pasa rápido: diluir y administrar en 15 min. Riesgo serotoninérgico.' },
  { id: 'nalbufina', n: 'Nalbufina', c: 'opio',
    bol: { u: 'mg', lo: 2.5, hi: 5, tope: 10, via: 'IV', dil: { m: 10, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Prurito por opioide neuroaxial: 2.5–5 mg. Agonista-antagonista: puede revertir analgesia.' },
  { id: 'meperidina', n: 'Meperidina', a: ['petidina'], c: 'opio',
    bol: { u: 'mg', lo: 12.5, hi: 25, tope: 50, via: 'IV', dil: { m: 100, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Escalofrío postanestésico: 12.5–25 mg IV. Evitar en renales (normeperidina) y con IMAO.' },

  /* ---------- ANALGESIA NO OPIOIDE ---------- */
  { id: 'paracetamol', n: 'Paracetamol IV', a: ['acetaminofen'], c: 'analg', fav: 1,
    bol: { u: 'mg/kg', lo: 12.5, hi: 15, tope: 1000, via: 'IV en 15 min', dil: { m: 1000, um: 'mg', v: 100, d: 'solución lista' } },
    nota: 'Máx 4 g/día (3 g si peso <50 kg, hepatopatía o alcoholismo). Intervalo 6 h.' },
  { id: 'dipirona', n: 'Dipirona (metamizol)', c: 'analg', fav: 1,
    bol: { u: 'mg/kg', lo: 20, hi: 40, tope: 2500, via: 'IV lento', dil: { m: 2500, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    nota: 'Pasar en 15 min diluida: en bolo produce hipotensión. Máx 6 g/día.' },
  { id: 'ketorolaco', n: 'Ketorolaco', c: 'analg',
    bol: { u: 'mg', lo: 15, hi: 30, tope: 30, via: 'IV', dil: { m: 30, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Máx 5 días, 120 mg/día. Reducir a 15 mg si >65 años o <50 kg. Evitar en sangrado o injerto óseo.' },
  { id: 'diclofenaco', n: 'Diclofenaco', c: 'analg',
    bol: { u: 'mg', lo: 37.5, hi: 75, tope: 75, via: 'IV en 30 min', dil: { m: 75, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    nota: 'Máx 150 mg/día. Contraindicado en ERC avanzada.' },
  { id: 'ibuprofeno-iv', n: 'Ibuprofeno IV', c: 'analg',
    bol: { u: 'mg', lo: 400, hi: 800, tope: 800, via: 'IV en 30 min', dil: { m: 800, um: 'mg', v: 200, d: 'SSN 0.9%' } },
    nota: 'Máx 3.2 g/día. Diluir siempre ≤4 mg/mL.' },
  { id: 'magnesio', n: 'Sulfato de magnesio', c: 'analg', fav: 1,
    inf: { u: 'g/hr', lo: 1, hi: 2, dil: { m: 10, um: 'g', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 30, hi: 50, tope: 4000, via: 'IV en 15 min', dil: { m: 2, um: 'g', v: 100, d: 'SSN 0.9%' } },
    nota: 'Coadyuvante analgésico 30–50 mg/kg + 10 mg/kg/hr. Preeclampsia: 4–6 g en 20 min y 1–2 g/hr. Vigilar reflejo rotuliano y diuresis. Antídoto: gluconato de calcio 1 g.' },
  { id: 'clonidina', n: 'Clonidina', c: 'analg',
    bol: { u: 'mcg/kg', lo: 1, hi: 2, tope: 150, via: 'IV lento', dil: { m: 150, um: 'mcg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Neuroaxial 1–2 µg/kg prolonga el bloqueo. Hipotensión, bradicardia y sedación.' },
  { id: 'dexametasona-analg', n: 'Dexametasona', c: 'analg', fav: 1,
    bol: { u: 'mg', lo: 4, hi: 8, tope: 8, via: 'IV', dil: { m: 8, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'PONV y coadyuvante analgésico: 4–8 mg a la inducción. Vigilar glucemia. Prolonga bloqueos periféricos.' },

  /* ---------- RELAJANTES ---------- */
  { id: 'rocuronio', n: 'Rocuronio', c: 'nmb', fav: 1, pref: 'ideal',
    inf: { u: 'mcg/kg/min', lo: 5, hi: 12, dil: { m: 100, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 0.6, hi: 1.2, via: 'IV', dil: { m: 50, um: 'mg', v: 5, d: 'sin diluir' } },
    nota: 'Intubación 0.6 mg/kg (60 s) · secuencia rápida 1.0–1.2 mg/kg (45 s). Mantenimiento 0.15 mg/kg. Reversión inmediata con sugammadex 16 mg/kg.' },
  { id: 'succinilcolina', n: 'Succinilcolina', a: ['suxametonio'], c: 'nmb', alerta: 1,
    bol: { u: 'mg/kg', lo: 1, hi: 1.5, tope: 150, via: 'IV', dil: { m: 100, um: 'mg', v: 5, d: 'sin diluir' } },
    nota: 'IM 3–4 mg/kg. Contraindicada en quemados >24 h, denervación, hiperpotasemia y antecedente de HM. Bradicardia en niños: atropinizar.' },
  { id: 'cisatracurio', n: 'Cisatracurio', c: 'nmb', fav: 1,
    inf: { u: 'mcg/kg/min', lo: 1, hi: 3, dil: { m: 20, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 0.15, hi: 0.2, via: 'IV', dil: { m: 10, um: 'mg', v: 5, d: 'sin diluir' } },
    nota: 'Eliminación de Hofmann: de elección en falla renal y hepática.' },
  { id: 'atracurio', n: 'Atracurio', c: 'nmb',
    inf: { u: 'mcg/kg/min', lo: 5, hi: 10, dil: { m: 50, um: 'mg', v: 50, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 0.4, hi: 0.5, via: 'IV', dil: { m: 50, um: 'mg', v: 5, d: 'sin diluir' } },
    nota: 'Libera histamina con bolos rápidos.' },
  { id: 'vecuronio', n: 'Vecuronio', c: 'nmb',
    inf: { u: 'mcg/kg/min', lo: 0.8, hi: 1.2, dil: { m: 20, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 0.08, hi: 0.1, via: 'IV', dil: { m: 10, um: 'mg', v: 10, d: 'agua estéril' } },
    nota: 'Acumula en falla renal. Reversible con sugammadex.' },
  { id: 'pancuronio', n: 'Pancuronio', c: 'nmb',
    bol: { u: 'mg/kg', lo: 0.08, hi: 0.1, via: 'IV', dil: { m: 4, um: 'mg', v: 2, d: 'sin diluir' } },
    nota: 'Acción larga (60–90 min). Taquicardia vagolítica.' },
  { id: 'mivacurio', n: 'Mivacurio', c: 'nmb',
    inf: { u: 'mcg/kg/min', lo: 4, hi: 10, dil: { m: 20, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 0.15, hi: 0.25, via: 'IV', dil: { m: 10, um: 'mg', v: 5, d: 'sin diluir' } },
    nota: 'Metabolismo por colinesterasa plasmática: bloqueo prolongado si es atípica.' },

  /* ---------- REVERSORES / ANTÍDOTOS ---------- */
  { id: 'sugammadex', n: 'Sugammadex', a: ['bridion'], c: 'rev', fav: 1,
    bol: { u: 'mg/kg', lo: 2, hi: 16, via: 'IV', dil: { m: 200, um: 'mg', v: 2, d: 'sin diluir (100 mg/mL)' } },
    nota: '2 mg/kg si TOF ≥2 · 4 mg/kg en bloqueo profundo (PTC 1–2) · 16 mg/kg reversión inmediata tras rocuronio 1.2 mg/kg. Usar PESO REAL. Anticoncepción hormonal ineficaz 7 días.' },
  { id: 'neostigmina', n: 'Neostigmina', c: 'rev',
    bol: { u: 'mcg/kg', lo: 40, hi: 70, tope: 5000, via: 'IV', dil: { m: 2.5, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Siempre con antimuscarínico (glicopirrolato 10 µg/kg o atropina 20 µg/kg). Requiere TOF ≥2. Máx 5 mg.' },
  { id: 'glicopirrolato', n: 'Glicopirrolato', c: 'rev',
    bol: { u: 'mcg/kg', lo: 5, hi: 10, tope: 600, via: 'IV', dil: { m: 0.6, um: 'mg', v: 3, d: 'sin diluir' } },
    nota: '0.2 mg por cada 1 mg de neostigmina. No cruza barrera hematoencefálica.' },
  { id: 'atropina', n: 'Atropina', c: 'rev', fav: 1,
    bol: { u: 'mcg/kg', lo: 10, hi: 20, tope: 1000, via: 'IV', dil: { m: 1, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Dosis mínima 0.1 mg (dosis menores producen bradicardia paradójica). Bradicardia adulto: 0.5–1 mg.' },
  { id: 'naloxona', n: 'Naloxona', c: 'rev', fav: 1,
    inf: { u: 'mcg/kg/hr', lo: 2, hi: 5, dil: { m: 2, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mcg', lo: 40, hi: 100, tope: 400, via: 'IV', dil: { m: 400, um: 'mcg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Titular 40 µg cada 2 min para no perder la analgesia. Vida media más corta que la del opioide: vigilar renarcotización.' },
  { id: 'flumazenil', n: 'Flumazenil', c: 'rev',
    bol: { u: 'mg', lo: 0.1, hi: 0.2, tope: 1, via: 'IV', dil: { m: 0.5, um: 'mg', v: 5, d: 'sin diluir' } },
    nota: '0.2 mg cada minuto hasta 1 mg. Riesgo de convulsión si hay dependencia a benzodiacepinas o antidepresivos tricíclicos.' },
  { id: 'dantroleno', n: 'Dantroleno', c: 'rev', alerta: 1,
    bol: { u: 'mg/kg', lo: 2.5, hi: 10, via: 'IV rápido', dil: { m: 20, um: 'mg', v: 60, d: 'agua estéril' } },
    nota: 'Hipertermia maligna: 2.5 mg/kg repetible hasta 10 mg/kg. Presentación nueva (Ryanodex) 250 mg en 5 mL.' },
  { id: 'intralipid', n: 'Emulsión lipídica 20%', a: ['intralipid'], c: 'rev', alerta: 1,
    inf: { u: 'mL/kg/hr', lo: 15, hi: 15, dil: { m: 1, um: 'mL', v: 1, d: 'sin diluir' } },
    bol: { u: 'mL/kg', lo: 1.5, hi: 1.5, via: 'IV en 1 min', dil: { m: 1, um: 'mL', v: 1, d: 'sin diluir' } },
    nota: 'Toxicidad por anestésico local: bolo 1.5 mL/kg + infusión 0.25 mL/kg/min (=15 mL/kg/hr). Repetir bolo ×2 si persiste el colapso. Máx 12 mL/kg.' },

  /* ---------- VASOPRESORES / INOTRÓPICOS ---------- */
  { id: 'noradrenalina', n: 'Noradrenalina', a: ['norepinefrina', 'levophed'], c: 'vaso', fav: 1, alerta: 1,
    inf: { u: 'mcg/kg/min', lo: 0.01, hi: 1, dil: { m: 4, um: 'mg', v: 100, d: 'DAD 5%' } },
    bol: { u: 'mcg', lo: 5, hi: 20, tope: 50, via: 'IV', dil: { m: 100, um: 'mcg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Primera línea en shock séptico y vasoplejía. Vía central preferente; periférica solo transitoria y en vena gruesa. Extravasación: fentolamina.' },
  { id: 'adrenalina', n: 'Adrenalina', a: ['epinefrina'], c: 'vaso', fav: 1, alerta: 1,
    inf: { u: 'mcg/kg/min', lo: 0.01, hi: 0.5, dil: { m: 4, um: 'mg', v: 100, d: 'DAD 5%' } },
    bol: { u: 'mcg', lo: 10, hi: 100, tope: 1000, via: 'IV', dil: { m: 1, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Paro: 1 mg cada 3–5 min. Anafilaxia: 0.5 mg IM (0.01 mg/kg) o 10–50 µg IV titulados. Broncoespasmo refractario: infusión.' },
  { id: 'fenilefrina', n: 'Fenilefrina', c: 'vaso', fav: 1,
    inf: { u: 'mcg/kg/min', lo: 0.1, hi: 1, dil: { m: 10, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mcg', lo: 50, hi: 200, tope: 500, via: 'IV', dil: { m: 1000, um: 'mcg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Alfa puro: eleva PA con bradicardia refleja. De elección en hipotensión por raquídea en obstetricia.' },
  { id: 'efedrina', n: 'Efedrina', c: 'vaso', fav: 1,
    bol: { u: 'mg', lo: 5, hi: 10, tope: 50, via: 'IV', dil: { m: 50, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: '5–10 mg repetible. Taquifilaxia tras 3–4 dosis. Preferible si hay bradicardia asociada.' },
  { id: 'vasopresina', n: 'Vasopresina', c: 'vaso', alerta: 1,
    inf: { u: 'U/hr', lo: 0.6, hi: 2.4, dil: { m: 20, um: 'U', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'U', lo: 1, hi: 2, tope: 4, via: 'IV', dil: { m: 20, um: 'U', v: 20, d: 'SSN 0.9%' } },
    nota: '0.01–0.04 U/min (=0.6–2.4 U/hr), dosis fija sin titular. Ahorra catecolaminas. No aumentar por encima de 0.04 U/min (isquemia).' },
  { id: 'dobutamina', n: 'Dobutamina', c: 'vaso', fav: 1,
    inf: { u: 'mcg/kg/min', lo: 2.5, hi: 20, dil: { m: 250, um: 'mg', v: 100, d: 'DAD 5%' } },
    nota: 'Inotrópico beta-1. Puede bajar la PA por vasodilatación beta-2: asegurar precarga y vasopresor de respaldo.' },
  { id: 'dopamina', n: 'Dopamina', c: 'vaso',
    inf: { u: 'mcg/kg/min', lo: 2, hi: 20, dil: { m: 400, um: 'mg', v: 250, d: 'DAD 5%' } },
    nota: '2–5 dopaminérgica · 5–10 beta · >10 alfa. Más arritmias que noradrenalina.' },
  { id: 'milrinona', n: 'Milrinona', c: 'vaso',
    inf: { u: 'mcg/kg/min', lo: 0.25, hi: 0.75, dil: { m: 20, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mcg/kg', lo: 25, hi: 50, via: 'IV en 10 min', dil: { m: 20, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    nota: 'Inodilatador. Carga opcional (hipotensión). Ajustar en falla renal.' },
  { id: 'levosimendan', n: 'Levosimendán', c: 'vaso',
    inf: { u: 'mcg/kg/min', lo: 0.05, hi: 0.2, dil: { m: 12.5, um: 'mg', v: 500, d: 'DAD 5%' } },
    nota: 'Infusión 24 h. Carga 6–12 µg/kg solo si la PA lo permite. Efecto persiste días (metabolito activo).' },
  { id: 'isoproterenol', n: 'Isoproterenol', c: 'vaso',
    inf: { u: 'mcg/min', lo: 0.5, hi: 10, dil: { m: 1, um: 'mg', v: 100, d: 'DAD 5%' } },
    nota: 'Bradicardia refractaria, bloqueo AV, torsades. Aumenta consumo miocárdico de O2.' },
  { id: 'metaraminol', n: 'Metaraminol', c: 'vaso',
    inf: { u: 'mcg/kg/min', lo: 0.5, hi: 5, dil: { m: 10, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mg', lo: 0.5, hi: 1, tope: 2, via: 'IV', dil: { m: 10, um: 'mg', v: 20, d: 'SSN 0.9%' } },
    nota: 'Alternativa a fenilefrina donde esté disponible.' },
  { id: 'azul-metileno', n: 'Azul de metileno', c: 'vaso',
    bol: { u: 'mg/kg', lo: 1, hi: 2, tope: 200, via: 'IV en 20 min', dil: { m: 100, um: 'mg', v: 100, d: 'DAD 5%' } },
    nota: 'Vasoplejía refractaria y metahemoglobinemia. Contraindicado con ISRS (síndrome serotoninérgico) y en déficit de G6PD.' },
  { id: 'cloruro-calcio', n: 'Cloruro de calcio 10%', c: 'vaso',
    bol: { u: 'mg/kg', lo: 10, hi: 20, tope: 1000, via: 'IV central lento', dil: { m: 1, um: 'g', v: 10, d: 'sin diluir' } },
    nota: '3× más calcio elemental que el gluconato. Vía central: es esclerosante.' },
  { id: 'gluconato-calcio', n: 'Gluconato de calcio 10%', c: 'vaso',
    bol: { u: 'mg/kg', lo: 30, hi: 60, tope: 3000, via: 'IV lento', dil: { m: 1, um: 'g', v: 10, d: 'sin diluir' } },
    nota: 'Hiperpotasemia, hipocalcemia por citrato en transfusión masiva, toxicidad por magnesio.' },

  /* ---------- VASODILATADORES / ANTIHIPERTENSIVOS ---------- */
  { id: 'nitroglicerina', n: 'Nitroglicerina', c: 'vdil', fav: 1,
    inf: { u: 'mcg/kg/min', lo: 0.1, hi: 3, dil: { m: 50, um: 'mg', v: 250, d: 'DAD 5%' } },
    nota: 'Venodilatador predominante. Tolerancia en 24 h. Contraindicada con inhibidores de PDE5 en 24–48 h.' },
  { id: 'nitroprusiato', n: 'Nitroprusiato de sodio', c: 'vdil', alerta: 1,
    inf: { u: 'mcg/kg/min', lo: 0.3, hi: 2, dil: { m: 50, um: 'mg', v: 250, d: 'DAD 5%' } },
    nota: 'Máx 8 µg/kg/min y nunca >10 min a dosis máxima: toxicidad por cianuro. Proteger de la luz.' },
  { id: 'nicardipino', n: 'Nicardipino', c: 'vdil',
    inf: { u: 'mg/hr', lo: 3, hi: 15, dil: { m: 25, um: 'mg', v: 250, d: 'SSN 0.9%' } },
    nota: 'Iniciar 5 mg/hr, subir 2.5 mg/hr cada 5–15 min. Sin efecto inotrópico negativo relevante.' },
  { id: 'clevidipino', n: 'Clevidipino', c: 'vdil',
    inf: { u: 'mg/hr', lo: 1, hi: 16, dil: { m: 25, um: 'mg', v: 50, d: 'emulsión lista' } },
    nota: 'Inicio 1–2 min. Aporta lípidos: contar el volumen. Contraindicado en alergia a soya/huevo.' },
  { id: 'esmolol', n: 'Esmolol', c: 'vdil', fav: 1,
    inf: { u: 'mcg/kg/min', lo: 50, hi: 200, dil: { m: 2500, um: 'mg', v: 250, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 0.25, hi: 0.5, tope: 100, via: 'IV en 30 s', dil: { m: 100, um: 'mg', v: 10, d: 'sin diluir' } },
    nota: 'Beta-1 selectivo, vida media 9 min. Ideal para respuesta a laringoscopia y taquicardia perioperatoria.' },
  { id: 'labetalol', n: 'Labetalol', c: 'vdil', fav: 1,
    inf: { u: 'mg/hr', lo: 20, hi: 160, dil: { m: 200, um: 'mg', v: 200, d: 'SSN 0.9%' } },
    bol: { u: 'mg', lo: 5, hi: 20, tope: 80, via: 'IV en 2 min', dil: { m: 100, um: 'mg', v: 20, d: 'sin diluir' } },
    nota: 'Bolos escalonados 5–10–20–40–80 mg cada 10 min (máx acumulado 300 mg). De elección en emergencia hipertensiva del embarazo.' },
  { id: 'hidralazina', n: 'Hidralazina', c: 'vdil',
    bol: { u: 'mg', lo: 5, hi: 10, tope: 20, via: 'IV', dil: { m: 20, um: 'mg', v: 20, d: 'SSN 0.9%' } },
    nota: 'Inicio 10–20 min, duración 4–6 h. Taquicardia refleja. Segunda línea en preeclampsia severa.' },
  { id: 'metoprolol', n: 'Metoprolol IV', c: 'vdil',
    bol: { u: 'mg', lo: 2.5, hi: 5, tope: 15, via: 'IV lento', dil: { m: 5, um: 'mg', v: 5, d: 'sin diluir' } },
    nota: '2.5–5 mg cada 5 min hasta 15 mg. Evitar en falla cardiaca descompensada y broncoespasmo.' },
  { id: 'urapidil', n: 'Urapidil', c: 'vdil',
    inf: { u: 'mg/hr', lo: 5, hi: 40, dil: { m: 250, um: 'mg', v: 250, d: 'SSN 0.9%' } },
    bol: { u: 'mg', lo: 12.5, hi: 25, tope: 50, via: 'IV', dil: { m: 50, um: 'mg', v: 10, d: 'sin diluir' } },
    nota: 'Alfa-1 bloqueante con acción central: poca taquicardia refleja.' },

  /* ---------- ANTIARRÍTMICOS ---------- */
  { id: 'amiodarona', n: 'Amiodarona', c: 'arrit', fav: 1,
    inf: { u: 'mg/min', lo: 0.5, hi: 1, dil: { m: 900, um: 'mg', v: 500, d: 'DAD 5%' } },
    bol: { u: 'mg/kg', lo: 5, hi: 5, tope: 300, via: 'IV en 10 min', dil: { m: 150, um: 'mg', v: 100, d: 'DAD 5%' } },
    nota: 'Paro con FV/TVsp: 300 mg en bolo, segunda dosis 150 mg. Luego 1 mg/min ×6 h y 0.5 mg/min ×18 h. Solo en DAD 5%.' },
  { id: 'adenosina', n: 'Adenosina', c: 'arrit', fav: 1,
    bol: { u: 'mg', lo: 6, hi: 12, tope: 18, via: 'IV rápido + bolo de SSN', dil: { m: 6, um: 'mg', v: 2, d: 'sin diluir' } },
    nota: '6 mg → 12 mg → 12 mg. Vena proximal, empuje rápido con 20 mL de SSN y brazo elevado. Pediatría 0.1 mg/kg (máx 6 mg).' },
  { id: 'lidocaina-arr', n: 'Lidocaína (antiarrítmico)', c: 'arrit',
    inf: { u: 'mg/min', lo: 1, hi: 4, dil: { m: 2, um: 'g', v: 500, d: 'DAD 5%' } },
    bol: { u: 'mg/kg', lo: 1, hi: 1.5, tope: 100, via: 'IV', dil: { m: 200, um: 'mg', v: 10, d: 'lidocaína 2%' } },
    nota: 'FV/TV refractaria: 1–1.5 mg/kg, repetir 0.5–0.75 mg/kg. Máx acumulado 3 mg/kg.' },
  { id: 'diltiazem', n: 'Diltiazem', c: 'arrit',
    inf: { u: 'mg/hr', lo: 5, hi: 15, dil: { m: 100, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 0.25, hi: 0.35, tope: 25, via: 'IV en 2 min', dil: { m: 25, um: 'mg', v: 25, d: 'SSN 0.9%' } },
    nota: 'FA con respuesta rápida. Evitar en FE reducida y en WPW.' },
  { id: 'verapamilo', n: 'Verapamilo', c: 'arrit',
    bol: { u: 'mg', lo: 2.5, hi: 5, tope: 20, via: 'IV en 2 min', dil: { m: 5, um: 'mg', v: 2, d: 'sin diluir' } },
    nota: 'No usar con betabloqueador IV ni en WPW. Antídoto: calcio.' },
  { id: 'digoxina', n: 'Digoxina', c: 'arrit',
    bol: { u: 'mcg/kg', lo: 8, hi: 12, tope: 500, via: 'IV lento', dil: { m: 500, um: 'mcg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Digitalización 0.25 mg cada 6 h hasta 1–1.5 mg. Ajustar en falla renal. Vigilar potasio.' },
  { id: 'sotalol', n: 'Sotalol IV', c: 'arrit',
    bol: { u: 'mg/kg', lo: 1, hi: 1.5, tope: 100, via: 'IV en 20 min', dil: { m: 100, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    nota: 'Prolonga QT: monitorizar. Contraindicado si QTc >450 ms.' },
  { id: 'procainamida', n: 'Procainamida', c: 'arrit',
    inf: { u: 'mg/min', lo: 1, hi: 4, dil: { m: 1, um: 'g', v: 250, d: 'DAD 5%' } },
    bol: { u: 'mg/kg', lo: 15, hi: 17, tope: 1000, via: 'IV a 20–50 mg/min', dil: { m: 1, um: 'g', v: 100, d: 'SSN 0.9%' } },
    nota: 'Detener si el QRS se ensancha >50 %, hay hipotensión o se alcanza 17 mg/kg.' },

  /* ---------- ANTIEMÉTICOS / NEURO ---------- */
  { id: 'ondansetron', n: 'Ondansetrón', c: 'emet', fav: 1,
    bol: { u: 'mg', lo: 4, hi: 8, tope: 16, via: 'IV lento', dil: { m: 8, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: '4 mg al final de la cirugía. Pediatría 0.1 mg/kg (máx 4 mg). Prolonga QT: máx 16 mg por dosis.' },
  { id: 'metoclopramida', n: 'Metoclopramida', c: 'emet',
    bol: { u: 'mg', lo: 10, hi: 10, tope: 20, via: 'IV lento', dil: { m: 10, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Poco efecto como antiemético profiláctico único. Riesgo de distonía; evitar en Parkinson.' },
  { id: 'droperidol', n: 'Droperidol', c: 'emet',
    bol: { u: 'mg', lo: 0.625, hi: 1.25, tope: 2.5, via: 'IV', dil: { m: 2.5, um: 'mg', v: 5, d: 'SSN 0.9%' } },
    nota: 'Muy eficaz en PONV a dosis bajas. Vigilar QT.' },
  { id: 'granisetron', n: 'Granisetrón', c: 'emet',
    bol: { u: 'mg', lo: 0.5, hi: 1, tope: 3, via: 'IV', dil: { m: 1, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Alternativa de acción más prolongada al ondansetrón.' },
  { id: 'difenhidramina', n: 'Difenhidramina', c: 'emet',
    bol: { u: 'mg', lo: 25, hi: 50, tope: 50, via: 'IV', dil: { m: 50, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Antihistamínico H1: anafilaxia (adyuvante), distonía, prurito.' },
  { id: 'haloperidol', n: 'Haloperidol', c: 'emet',
    bol: { u: 'mg', lo: 0.5, hi: 2, tope: 5, via: 'IV', dil: { m: 5, um: 'mg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Delirium postoperatorio y PONV refractario. Vigilar QT.' },
  { id: 'fenitoina', n: 'Fenitoína', c: 'emet',
    bol: { u: 'mg/kg', lo: 15, hi: 20, tope: 1500, via: 'IV máx 50 mg/min', dil: { m: 1, um: 'g', v: 100, d: 'SSN 0.9% (no dextrosa)' } },
    nota: 'Nunca >50 mg/min (hipotensión, arritmia). Solo en SSN: precipita en dextrosa. Monitorizar ECG y PA.' },
  { id: 'levetiracetam', n: 'Levetiracetam', c: 'emet',
    bol: { u: 'mg/kg', lo: 20, hi: 60, tope: 4500, via: 'IV en 15 min', dil: { m: 1500, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    nota: 'Estatus: 60 mg/kg (máx 4500 mg). Pocas interacciones; ajustar en falla renal.' },

  /* ---------- ANTIBIÓTICOS ---------- */
  { id: 'cefazolina', n: 'Cefazolina', c: 'atb', fav: 1,
    bol: { u: 'mg/kg', lo: 25, hi: 30, tope: 3000, via: 'IV en 15 min', dil: { m: 2, um: 'g', v: 100, d: 'SSN 0.9%' } },
    nota: 'Profilaxis: 2 g (3 g si >120 kg) 30–60 min antes de la incisión. Redosificar a las 4 h o si el sangrado supera 1500 mL.' },
  { id: 'cefuroxima', n: 'Cefuroxima', c: 'atb',
    bol: { u: 'mg/kg', lo: 20, hi: 30, tope: 1500, via: 'IV en 15 min', dil: { m: 1.5, um: 'g', v: 100, d: 'SSN 0.9%' } },
    nota: 'Profilaxis 1.5 g. Redosificar a las 4 h.' },
  { id: 'ceftriaxona', n: 'Ceftriaxona', c: 'atb',
    bol: { u: 'mg/kg', lo: 50, hi: 75, tope: 2000, via: 'IV en 30 min', dil: { m: 2, um: 'g', v: 100, d: 'SSN 0.9%' } },
    nota: 'No mezclar con soluciones con calcio (Ringer lactato).' },
  { id: 'ampi-sulbactam', n: 'Ampicilina/sulbactam', c: 'atb',
    bol: { u: 'mg/kg', lo: 50, hi: 50, tope: 3000, via: 'IV en 30 min', dil: { m: 3, um: 'g', v: 100, d: 'SSN 0.9%' } },
    nota: 'Profilaxis 3 g. Redosificar a las 2 h.' },
  { id: 'clindamicina', n: 'Clindamicina', c: 'atb',
    bol: { u: 'mg/kg', lo: 10, hi: 10, tope: 900, via: 'IV en 30 min', dil: { m: 900, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    nota: 'Alternativa en alergia a betalactámicos. Nunca en bolo rápido. Redosificar a las 6 h.' },
  { id: 'vancomicina', n: 'Vancomicina', c: 'atb', alerta: 1,
    inf: { u: 'mg/hr', lo: 500, hi: 1000, dil: { m: 1, um: 'g', v: 250, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 15, hi: 20, tope: 2000, via: 'IV ≥60 min', dil: { m: 1, um: 'g', v: 250, d: 'SSN 0.9%' } },
    nota: 'Máx 10 mg/min: infusión rápida = síndrome del hombre rojo. Iniciar 60–120 min antes de la incisión.' },
  { id: 'gentamicina', n: 'Gentamicina', c: 'atb',
    bol: { u: 'mg/kg', lo: 5, hi: 7, tope: 600, via: 'IV en 30 min', dil: { m: 240, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    nota: 'Dosis única diaria. Usar peso ajustado si IMC alto. Nefro y ototóxico; potencia el bloqueo neuromuscular.' },
  { id: 'amikacina', n: 'Amikacina', c: 'atb',
    bol: { u: 'mg/kg', lo: 15, hi: 20, tope: 1500, via: 'IV en 30 min', dil: { m: 1, um: 'g', v: 100, d: 'SSN 0.9%' } },
    nota: 'Dosis única diaria, ajustar por función renal.' },
  { id: 'metronidazol', n: 'Metronidazol', c: 'atb',
    bol: { u: 'mg/kg', lo: 15, hi: 15, tope: 500, via: 'IV en 30 min', dil: { m: 500, um: 'mg', v: 100, d: 'solución lista' } },
    nota: 'Profilaxis colorrectal junto con cefazolina.' },
  { id: 'pip-tazo', n: 'Piperacilina/tazobactam', c: 'atb',
    bol: { u: 'mg/kg', lo: 75, hi: 100, tope: 4500, via: 'IV en 30 min', dil: { m: 4.5, um: 'g', v: 100, d: 'SSN 0.9%' } },
    nota: '4.5 g cada 6–8 h. Infusión extendida (4 h) mejora el perfil PK/PD.' },
  { id: 'meropenem', n: 'Meropenem', c: 'atb',
    bol: { u: 'mg/kg', lo: 20, hi: 40, tope: 2000, via: 'IV en 30 min', dil: { m: 1, um: 'g', v: 100, d: 'SSN 0.9%' } },
    nota: '1–2 g cada 8 h. Reduce niveles de ácido valproico.' },
  { id: 'ciprofloxacino', n: 'Ciprofloxacino', c: 'atb',
    bol: { u: 'mg', lo: 400, hi: 400, tope: 400, via: 'IV en 60 min', dil: { m: 400, um: 'mg', v: 200, d: 'solución lista' } },
    nota: 'Prolonga QT. Tendinopatía.' },

  /* ---------- HEMOSTASIA / ANTICOAGULACIÓN ---------- */
  { id: 'tranexamico', n: 'Ácido tranexámico', a: ['txa'], c: 'hemo', fav: 1,
    inf: { u: 'mg/kg/hr', lo: 1, hi: 2, dil: { m: 1000, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 10, hi: 15, tope: 1000, via: 'IV en 10 min', dil: { m: 1000, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    nota: 'Trauma/CRASH-2: 1 g en 10 min + 1 g en 8 h, dentro de las 3 primeras horas. Ortopedia: 15 mg/kg preincisión. NUNCA por vía neuroaxial (confusión con bupivacaína: convulsiones y muerte).' },
  { id: 'heparina', n: 'Heparina no fraccionada', c: 'hemo', alerta: 1,
    inf: { u: 'U/kg/hr', lo: 12, hi: 18, dil: { m: 25000, um: 'U', v: 250, d: 'SSN 0.9%' } },
    bol: { u: 'U/kg', lo: 80, hi: 100, tope: 10000, via: 'IV', dil: { m: 5000, um: 'U', v: 5, d: 'sin diluir' } },
    nota: 'CEC: 300–400 U/kg con objetivo TCA >480 s. Anticoagulación terapéutica: 80 U/kg + 18 U/kg/hr, ajustar por TTPa.' },
  { id: 'protamina', n: 'Protamina', c: 'hemo', alerta: 1,
    bol: { u: 'mg', lo: 25, hi: 50, tope: 50, via: 'IV lento (≥10 min)', dil: { m: 50, um: 'mg', v: 50, d: 'SSN 0.9%' } },
    nota: '1 mg neutraliza ≈100 U de heparina circulante. Bolo rápido: hipotensión, hipertensión pulmonar y anafilaxia. Máx 50 mg por dosis.' },
  { id: 'insulina', n: 'Insulina regular', c: 'hemo', fav: 1, alerta: 1,
    inf: { u: 'U/hr', lo: 0.5, hi: 10, dil: { m: 50, um: 'U', v: 50, d: 'SSN 0.9% (purgar la línea)' } },
    bol: { u: 'U/kg', lo: 0.05, hi: 0.1, tope: 10, via: 'IV', dil: { m: 100, um: 'U', v: 100, d: 'SSN 0.9%' } },
    nota: 'Purgar 20 mL para saturar el plástico. Glucemia horaria. Hiperpotasemia: 10 U con 25 g de dextrosa.' },

  /* ---------- OBSTETRICIA ---------- */
  { id: 'oxitocina', n: 'Oxitocina', c: 'obst', fav: 1,
    inf: { u: 'U/hr', lo: 2.5, hi: 15, dil: { m: 20, um: 'U', v: 500, d: 'SSN 0.9%' } },
    bol: { u: 'U', lo: 1, hi: 3, tope: 5, via: 'IV lento (≥30 s)', dil: { m: 10, um: 'U', v: 10, d: 'SSN 0.9%' } },
    nota: 'Cesárea: 1–3 U lentas + infusión 5–10 U/hr. Bolo rápido: hipotensión, taquicardia, isquemia. Regla de los tres si no hay tono.' },
  { id: 'carbetocina', n: 'Carbetocina', c: 'obst',
    bol: { u: 'mcg', lo: 100, hi: 100, tope: 100, via: 'IV en 1 min', dil: { m: 100, um: 'mcg', v: 10, d: 'SSN 0.9%' } },
    nota: 'Dosis única de 100 µg tras el pinzamiento; sustituye la infusión de oxitocina.' },
  { id: 'metilergonovina', n: 'Metilergonovina', c: 'obst',
    bol: { u: 'mg', lo: 0.2, hi: 0.2, tope: 0.2, via: 'IM (preferente)', dil: { m: 0.2, um: 'mg', v: 1, d: 'sin diluir' } },
    nota: 'Segunda línea en atonía. Contraindicada en hipertensión y preeclampsia. IV solo en emergencia y muy lento.' },

  /* ---------- RESPIRATORIO / ESTEROIDES ---------- */
  { id: 'salbutamol', n: 'Salbutamol IV', a: ['albuterol'], c: 'resp',
    inf: { u: 'mcg/min', lo: 5, hi: 20, dil: { m: 5, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mcg/kg', lo: 5, hi: 10, tope: 250, via: 'IV en 5 min', dil: { m: 500, um: 'mcg', v: 50, d: 'SSN 0.9%' } },
    nota: 'Broncoespasmo refractario. Taquicardia, hipopotasemia y acidosis láctica.' },
  { id: 'aminofilina', n: 'Aminofilina', c: 'resp',
    inf: { u: 'mg/kg/hr', lo: 0.4, hi: 0.6, dil: { m: 250, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 5, hi: 6, tope: 500, via: 'IV en 20 min', dil: { m: 250, um: 'mg', v: 100, d: 'SSN 0.9%' } },
    nota: 'Margen terapéutico estrecho. Reducir la carga a la mitad si ya recibía teofilina.' },
  { id: 'hidrocortisona', n: 'Hidrocortisona', c: 'resp',
    bol: { u: 'mg', lo: 100, hi: 200, tope: 200, via: 'IV', dil: { m: 100, um: 'mg', v: 2, d: 'agua estéril' } },
    nota: 'Anafilaxia, insuficiencia suprarrenal, asma severa. Dosis de estrés 100 mg + 50 mg cada 8 h.' },
  { id: 'metilprednisolona', n: 'Metilprednisolona', c: 'resp',
    bol: { u: 'mg/kg', lo: 1, hi: 2, tope: 125, via: 'IV', dil: { m: 125, um: 'mg', v: 2, d: 'diluyente propio' } },
    nota: 'Broncoespasmo, edema de vía aérea, extubación de riesgo.' },

  /* ---------- METABÓLICO / ELECTROLITOS ---------- */
  { id: 'bicarbonato', n: 'Bicarbonato de sodio 8.4%', c: 'meta',
    bol: { u: 'mEq/kg', lo: 0.5, hi: 1, tope: 100, via: 'IV lento', dil: { m: 100, um: 'mEq', v: 100, d: 'sin diluir (1 mEq/mL)' } },
    nota: 'Acidosis severa, hiperpotasemia, intoxicación por tricíclicos, alcalinización urinaria. No mezclar con calcio.' },
  { id: 'potasio', n: 'Cloruro de potasio', c: 'meta', alerta: 1,
    inf: { u: 'mEq/hr', lo: 10, hi: 20, dil: { m: 40, um: 'mEq', v: 500, d: 'SSN 0.9%' } },
    nota: 'Periférica máx 10 mEq/hr y ≤40 mEq/L. Central hasta 20 mEq/hr con monitor. NUNCA en bolo.' },
  { id: 'manitol', n: 'Manitol 20%', c: 'meta',
    bol: { u: 'g/kg', lo: 0.25, hi: 1, tope: 100, via: 'IV en 20 min', dil: { m: 100, um: 'g', v: 500, d: 'solución lista' } },
    nota: 'Hipertensión intracraneal 0.25–1 g/kg. Filtro en línea. Vigilar osmolaridad (<320) y volemia.' },
  { id: 'dextrosa50', n: 'Dextrosa 50%', c: 'meta',
    bol: { u: 'g', lo: 12.5, hi: 25, tope: 50, via: 'IV lento', dil: { m: 25, um: 'g', v: 50, d: 'sin diluir (0.5 g/mL)' } },
    nota: 'Hipoglucemia: 25 g. Vía gruesa o central: es esclerosante. Pediatría: dextrosa 10 % 2–5 mL/kg.' },
  { id: 'furosemida', n: 'Furosemida', c: 'meta',
    inf: { u: 'mg/hr', lo: 2, hi: 20, dil: { m: 250, um: 'mg', v: 50, d: 'SSN 0.9%' } },
    bol: { u: 'mg/kg', lo: 0.5, hi: 1, tope: 80, via: 'IV lento', dil: { m: 20, um: 'mg', v: 2, d: 'sin diluir' } },
    nota: 'Máx 4 mg/min en bolo (ototoxicidad). En infusión rinde más que en bolos repetidos.' },
  { id: 'terlipresina', n: 'Terlipresina', c: 'meta',
    bol: { u: 'mg', lo: 1, hi: 2, tope: 2, via: 'IV', dil: { m: 1, um: 'mg', v: 5, d: 'SSN 0.9%' } },
    nota: 'Sangrado variceal y síndrome hepatorrenal: 1–2 mg cada 4–6 h. Vigilar isquemia.' },
];

export const SETS: SetFarmacos[] = [
  { id: 'tiva', n: 'TIVA propofol–remifentanilo', items: [
    { d: 'propofol', modo: 'inf', val: 6 },
    { d: 'remifentanilo', modo: 'inf', val: 0.15 }] },
  { id: 'tiva-dex', n: 'TIVA libre de opioide', items: [
    { d: 'propofol', modo: 'inf', val: 5 },
    { d: 'dexmedetomidina', modo: 'inf', val: 0.5 },
    { d: 'lidocaina-iv', modo: 'inf', val: 1.5 },
    { d: 'ketamina', modo: 'inf', val: 0.2 }] },
  { id: 'ketodex', n: 'Ketodex (sedación)', items: [
    { d: 'ketamina', modo: 'inf', val: 0.25 },
    { d: 'dexmedetomidina', modo: 'inf', val: 0.6 }] },
  { id: 'isr', n: 'Secuencia rápida', items: [
    { d: 'fentanilo', modo: 'bol', val: 2 },
    { d: 'propofol', modo: 'bol', val: 2 },
    { d: 'rocuronio', modo: 'bol', val: 1.2 }] },
  { id: 'septico', n: 'Shock séptico', items: [
    { d: 'noradrenalina', modo: 'inf', val: 0.1 },
    { d: 'vasopresina', modo: 'inf', val: 1.8 },
    { d: 'dobutamina', modo: 'inf', val: 5 }] },
  { id: 'cesarea', n: 'Cesárea — raquídea', items: [
    { d: 'fenilefrina', modo: 'inf', val: 0.5 },
    { d: 'oxitocina', modo: 'inf', val: 7.5 },
    { d: 'ondansetron', modo: 'bol', val: 4 },
    { d: 'cefazolina', modo: 'bol', val: 28 }] },
  { id: 'multimodal', n: 'Analgesia multimodal', items: [
    { d: 'paracetamol', modo: 'bol', val: 15 },
    { d: 'dipirona', modo: 'bol', val: 30 },
    { d: 'dexametasona-analg', modo: 'bol', val: 8 },
    { d: 'magnesio', modo: 'bol', val: 30 }] },
  { id: 'lastr', n: 'Toxicidad por anestésico local', items: [
    { d: 'intralipid', modo: 'bol', val: 1.5 },
    { d: 'intralipid', modo: 'inf', val: 15 },
    { d: 'adrenalina', modo: 'bol', val: 50 }] },
];

export const CATALOGO_SEMILLA: Catalogo = {
  version: SEED_VERSION,
  cats: CATS,
  drugs: DRUGS,
  sets: SETS,
};